# Generated by Django 4.0.2 on 2022-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_info_alter_customer_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='product_photo',
            field=models.ImageField(upload_to='product_img'),
        ),
    ]
