# Generated by Django 4.0.2 on 2022-02-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_product_info_auction_end_datetime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auctioned_product',
        ),
        migrations.DeleteModel(
            name='product_info',
        ),
    ]
