# Generated by Django 4.0.2 on 2022-02-22 04:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customer_profile_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 4, 45, 52, 173146, tzinfo=utc)),
        ),
    ]
