# Generated by Django 4.0.2 on 2022-02-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=1200)),
                ('product_photo', models.ImageField(upload_to='product_img')),
            ],
        ),
        migrations.CreateModel(
            name='auctioned_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_bid_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product_info')),
            ],
        ),
    ]
