# Generated by Django 4.0.2 on 2022-02-21 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioned_product',
            name='auction_end_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 19, 33, 5, 901246, tzinfo=utc)),
        ),
    ]
