# Generated by Django 4.0.2 on 2022-02-21 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auctioned_product_auction_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioned_product',
            name='auction_end_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 19, 34, 10, 300325, tzinfo=utc)),
        ),
    ]
