# Generated by Django 4.0.2 on 2022-02-22 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_auctioned_product_auction_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioned_product',
            name='auction_end_dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
