# Generated by Django 4.0.2 on 2022-02-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_auctioned_product_auction_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='product_description',
            field=models.TextField(max_length=1200),
        ),
    ]
