# Generated by Django 4.0.2 on 2022-03-17 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_info_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioned_product',
            name='auction_end_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 3, 18, 12, 882046, tzinfo=utc)),
        ),
    ]
