# Generated by Django 4.0.2 on 2022-03-03 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_product_info_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_bidding',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('final_bid', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product_info')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
